[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true

[rpc_endpoints]
# default is your local fork
default = "http://127.0.0.1:8545"
# mainnet 
mainnet = "${MAINNET_RPC_URL}"
